name: Embedded - AArch64 Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev
          sudo apt install g++-aarch64-linux-gnu 
          sudo apt install zip

      - name: Make staging directory
        run: mkdir -p staging/raspifx

      - name: Get Pi4J libs
        run: wget https://github.com/Pi4J/download/raw/main/pi4j-2.1.1.zip

      - name: Unzip Pi4J
        run: unzip pi4j-2.1.1.zip

      - name: Unzip pigpio.jar
        run: unzip -o pi4j-2.1.1/lib/pi4j-library-pigpio.jar

      - name: Copy libs to staging
        run: cp lib/aarch64/libpi4j-pigpio.so staging/raspifx

      - name: Gluon License
        uses: gluonhq/gluon-build-license@v1
        with:
          gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Gluon Build
        run:
          mvn -Ppi gluonfx:build gluonfx:package

      - name: Set permissions
        run: chmod +x target/gluonfx/aarch64-linux/RaspPiFX

      - name: Copy native image to staging
        run: cp -r target/gluonfx/aarch64-linux/RaspPiFX staging/raspifx

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
